#+STARTUP: content
#+STARTUP: overview
#+STARTUP: indent
#+TITLE: Tabuleiro de Combate de Peças (TCP)

TCP is an open-source, object-oriented implementation of the traditional Chess game, made for our final project for the "INF01120" course.

#+begin_quote
[!WARNING]
TCP is still under development, expect to find some bugs while testing/playing. Feel free to report or even send fixes!
#+end_quote

** Getting started
TCP intends to be an easy-to-play and beginner-friendly chess game. You can clone this repository and build the game with the following commands:

*** Linux (terminal):
#+begin_src
git clone https://github.com/SW-Engineering-Courses-Karina-Kohl/tcp-final-20251-grupo02.git tcp
cd tcp
make run
#+end_src

*** Windows (vscode/powershell):
#+begin_src
git clone https://github.com/SW-Engineering-Courses-Karina-Kohl/tcp-final-20251-grupo02.git tcp
cd tcp
javac -cp lib/jaylib-5.5.0-2.jar -d bin (Get-ChildItem -Recurse -Filter *.java -Path src).FullName
java -cp lib/jaylib-5.5.0-2.jar`;bin app.Main
#+end_src

** Tarefas

| ._subtarefas/Tarefas | Menu          | Jogo      | Movimentos               | Cheque-Mate                      | Fim       |
|---------------------+---------------+-----------+--------------------------+----------------------------------+-----------|
|                   1 | Novo Jogo     | Tabuleiro | Movimento para cada peça | Veficicação de possíveis defesas | Vencedor  |
|                   2 | Sair do Jogo  | Peças     | Captura de peças         | Derrota/Vitória                  | Novo Jogo |
|                   3 | Configurações | Turnos    | Promoção                 | Afogamento                       |           |
|                   4 |               | Relógio   | Movimentos especiais     | Repetição                        |           |
