name: Makefile CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build

    - name: Run Tests
      run: make test
